name = "wonderchan"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "journal_db"
database_id = "f89f2766-65a7-4034-83af-263c0e8de51a"
