name = "wchan"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"

# Cloudflare D1 Database Binding.
[[d1_databases]]
binding = "DB"
database_name = "wchan_db1"
database_id = "c1bc2b38-b29b-44f8-9d83-f4789443ab34"